//! Build script: bake the Google OAuth client pair into the binary in
//! obfuscated form.
//!
//! `hop auth gmail` needs a Google OAuth client. Google's Desktop-app clients
//! are not confidential (PKCE and the loopback redirect are the real
//! protection), and the pair necessarily ships inside every distributed
//! binary — so this is **obfuscation, not encryption**, and we say so plainly:
//! anyone determined can recover it from a release binary.
//!
//! What it does buy, which is the actual cost centre:
//!   * the repository contains no credential-shaped strings, so GitHub push
//!     protection never blocks maintainers or contributors,
//!   * automated scanners (GitHub, TruffleHog, gitleaks) file no alerts, and
//!     the beg-bounty mail those generate never starts,
//!   * `strings <binary>` does not surface it, so drive-by extraction takes
//!     deliberate effort rather than one command.
//!
//! Values come from the build environment (`HOP_GOOGLE_CLIENT_ID` /
//! `HOP_GOOGLE_CLIENT_SECRET`); a build without them simply has no default
//! client, and `hop auth gmail` explains how to supply one. Release builds set
//! them from CI secrets.

use std::{env, fs, path::PathBuf};

/// Fixed XOR pad. Not a secret (it ships in the binary too) — its only job is
/// to keep the credential out of `strings` output.
const PAD: &[u8] = b"wirehop/oauth/v1";

fn obfuscated(value: Option<String>) -> String {
    match value {
        Some(v) if !v.is_empty() => {
            let bytes: Vec<String> = v
                .as_bytes()
                .iter()
                .enumerate()
                .map(|(i, b)| (b ^ PAD[i % PAD.len()]).to_string())
                .collect();
            format!("Some(&[{}])", bytes.join(","))
        }
        _ => "None".to_string(),
    }
}

fn main() {
    println!("cargo:rerun-if-env-changed=HOP_GOOGLE_CLIENT_ID");
    println!("cargo:rerun-if-env-changed=HOP_GOOGLE_CLIENT_SECRET");

    let pad: Vec<String> = PAD.iter().map(|b| b.to_string()).collect();
    let generated = format!(
        "// @generated by build.rs — do not edit.\n\
         pub(crate) const OAUTH_PAD: &[u8] = &[{}];\n\
         pub(crate) const OAUTH_CLIENT_ID: Option<&[u8]> = {};\n\
         pub(crate) const OAUTH_CLIENT_SECRET: Option<&[u8]> = {};\n",
        pad.join(","),
        obfuscated(env::var("HOP_GOOGLE_CLIENT_ID").ok()),
        obfuscated(env::var("HOP_GOOGLE_CLIENT_SECRET").ok()),
    );

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("oauth_baked.rs");
    fs::write(&out, generated).expect("write oauth_baked.rs");
}
