[package]
name = "hop-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hop"
path = "src/main.rs"

[dependencies]
hop-core.workspace = true
iroh.workspace = true
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
crossterm.workspace = true
ratatui.workspace = true
serde.workspace = true
bincode.workspace = true
libc.workspace = true

[dev-dependencies]
tempfile.workspace = true
sha2 = "0.10"
